### ISSUE TITLE
Topic related separation on navigation level

### ISSUE THREAD

**Issue by Seinnd** [baguse/directus-extension-flow-manager#1]
As impressive as this extension is, considering the fact that in a larger environment (_even with a grouping option_) the overview suffers extremely. So I think it would be quite pleasant if the groups (_or a new grouping option for separation_) were placed on the navigation level instead of an endless list.

![image](https://github.com/baguse/directus-extension-flow-manager/assets/22862290/1a9f7042-3eef-486f-a338-30ba6496bf9f)

**Comment by baguse** [comment]
Hello, thanks @Seinnd. I will try to implement the improvement. Stay tuned

**Comment by baguse** [comment]
![image](https://github.com/baguse/directus-extension-flow-manager/assets/36828138/3211ac89-15ee-437c-97a8-8d0662f26a5e)
I'm planning to execute your idea like this. Any thoughts? @Seinnd

**Comment by Seinnd** [comment]
> ![image](https://private-user-images.githubusercontent.com/36828138/306928465-3211ac89-15ee-437c-97a8-8d0662f26a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDYwOTMsIm5iZiI6MTcwOTU0NTc5MywicGF0aCI6Ii8zNjgyODEzOC8zMDY5Mjg0NjUtMzIxMWFjODktMTVlZS00MzdjLTk3YTgtOGQwNjYyZjI2YTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTEyMTZmYTU1NmIzNmUzY2RkODFmMzM5OTE3YzJlZmViMTk0MTYwN2FiNDM3ZWFiOGNjMzg1MGNkYTRjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpaYSLXVR1mjbNcRf0iZfDwEs06Z7_KNOBaAPaQzk9w) I'm planning to execute your idea like this. Any thoughts? @Seinnd

This is exactly what user-friendliness should look like :-) great improvement so far — I am thrilled to finally have this in action

**Comment by baguse** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36828138/306928465-3211ac89-15ee-437c-97a8-8d0662f26a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDYwOTMsIm5iZiI6MTcwOTU0NTc5MywicGF0aCI6Ii8zNjgyODEzOC8zMDY5Mjg0NjUtMzIxMWFjODktMTVlZS00MzdjLTk3YTgtOGQwNjYyZjI2YTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTEyMTZmYTU1NmIzNmUzY2RkODFmMzM5OTE3YzJlZmViMTk0MTYwN2FiNDM3ZWFiOGNjMzg1MGNkYTRjOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpaYSLXVR1mjbNcRf0iZfDwEs06Z7_KNOBaAPaQzk9w) I'm planning to execute your idea like this. Any thoughts? @Seinnd
> 
> This is exactly what user-friendliness should look like :-) great improvement so far — I am thrilled to finally have this in action

Thank you, I planned to release it soon but there is a bug that I need to solve first
