### ISSUE TITLE
Export/Import All Flows in One Click?

### ISSUE THREAD

**Issue by JayShoe** [baguse/directus-extension-flow-manager#10]
Hello, 

This extension is where I live. Thank you so much for your work here, it's wonderful. 

Can we have an export ALL flows in one click? Can we have import ALL flows in one click?

This would be great for backup purposes, and could be used with GIT if it were one file that contained all the flows. 

If it were a zip file that would be OK too, 

Jay

**Comment by baguse** [comment]
Hi, thanks. I really appreciate it.

Ah nice idea, I will add it to the roadmap. My plan is to export it as json file.

**Comment by baguse** [comment]
Hello the issue close on v.1.4.1 Release
