### ISSUE TITLE
Extension not in the marketplace

### ISSUE THREAD

**Issue by JayShoe** [baguse/directus-extension-flow-manager#11]
Hello, 

I uninstalled the extension from my cloud and went to reinstall it to update it. But it is not currently on the directus marketplace for me to grab. Do you know why? I really need to grab the flows off this cloud account. 

Jay

**Comment by baguse** [comment]
@JayShoe Try to set the env `MARKETPLACE_TRUST=ALL`

**Comment by JayShoe** [comment]
Hi baguse,

I'm using this on a Pro Cloud instance and don't have access to the ENV. How long do you think until Directus approves the plugin? It's a shame the older one doesn't show up either. I might be able to use the "staging" version for now. But I really want to backup my Flows. I was hoping to use the "download all" function. :-)

Jay

**Comment by baguse** [comment]
> Hi baguse,
> 
> I'm using this on a Pro Cloud instance and don't have access to the ENV. How long do you think until Directus approves the plugin? It's a shame the older one doesn't show up either. I might be able to use the "staging" version for now. But I really want to backup my Flows. I was hoping to use the "download all" function. :-)
> 
> Jay

I'm sorry to hear that, honestly I don't know the estimation. Can you install it using npm install command?

**Comment by JayShoe** [comment]
Hello, 

I asked directus support why I can't add your extension and they said this. 

> After looking into "package.json" of "directus-extension-flow-manager" extension:
> 
> https://github.com/baguse/directus-extension-flow-manager/blob/master/package.json
> 
> We can see that sandbox is not enabled. This means that the extension is not secure so our Professional Cloud does not support it.
> 
> 
> In order to get it working on your project you either need to ask the extension author to enable sandbox mode: https://docs.directus.io/extensions/sandbox/introduction.html#creating-sandboxed-extensions
> 
> Or you could set "MARKETPLACE_TRUST" to "all", but this is only available for Enterprise tier.
> 

Would you mind making the necessary changes so I can use this in the directus cloud?

Jay

**Comment by baguse** [comment]
> Hello, 
> 
> I asked directus support why I can't add your extension and they said this. 
> 
> > After looking into "package.json" of "directus-extension-flow-manager" extension:
> > 
> > https://github.com/baguse/directus-extension-flow-manager/blob/master/package.json
> > 
> > We can see that sandbox is not enabled. This means that the extension is not secure so our Professional Cloud does not support it.
> > 
> > 
> > In order to get it working on your project you either need to ask the extension author to enable sandbox mode: https://docs.directus.io/extensions/sandbox/introduction.html#creating-sandboxed-extensions
> > 
> > Or you could set "MARKETPLACE_TRUST" to "all", but this is only available for Enterprise tier.
> > 
> 
> Would you mind making the necessary changes so I can use this in the directus cloud?
> 
> Jay
> 

Cool, thanks. I will fix it by today

**Comment by JayShoe** [comment]
Hello, I would appreciate it if you were able to help fix this. I really need the plugin so I can export my flows.

**Comment by baguse** [comment]
> Hello, I would appreciate it if you were able to help fix this. I really need the plugin so I can export my flows. 

Hi, sorry for the inconvenience. I tried to flagging as a sandbox but it's not helped. Another solution is to create a new extension w/o bundle it, but there are few things that not working. The export/import will be working

**Comment by JayShoe** [comment]
> Hi, sorry for the inconvenience. I tried to flagging as a sandbox but it's not helped. Another solution is to create a new extension w/o bundle it, but there are few things that not working. The export/import will be working

Hello, well I know I owe you a beer. I appreciate you and I'm sorry for the support request! Is there any function inside NPM or otherwise that would allow me to install the older version of this plugin? This seems to be an issue that directus might want to account for moving forward. Maybe I/we should fork the repo based on [V1.3.1](https://github.com/baguse/directus-extension-flow-manager/releases/tag/v1.3.1)? That was the last known working version, right?

**Comment by baguse** [comment]
> 
> > Hi, sorry for the inconvenience. I tried to flagging as a sandbox but it's not helped. Another solution is to create a new extension w/o bundle it, but there are few things that not working. The export/import will be working
> 
> Hello, well I know I owe you a beer. I appreciate you and I'm sorry for the support request! Is there any function inside NPM or otherwise that would allow me to install the older version of this plugin? This seems to be an issue that directus might want to account for moving forward. Maybe I/we should fork the repo based on [V1.3.1](https://github.com/baguse/directus-extension-flow-manager/releases/tag/v1.3.1)? That was the last known working version, right? 

No worries, I will be happy if this extension is useful for everyone. Yes, you can fork the extension on 1.3.1 or if possible you can install via npm with v1.3.1

**Comment by JayShoe** [comment]
TBH, I'm a little nervous about doing this and then having to get the extension to NPM etc... 

> I will be happy if this extension is useful for everyone. 

Is there any plan to get it back onto the marketplace?

**Comment by baguse** [comment]
> TBH, I'm a little nervous about doing this and then having to get the extension to NPM etc... 
> 
> > I will be happy if this extension is useful for everyone. 
> 
> Is there any plan to get it back onto the marketplace?

Ah ok, no worries. I will make it one, without some new features. Is it ok?

**Comment by JayShoe** [comment]
Yes, I would really appreciate it.

**Comment by baguse** [comment]
Hi @JayShoe, I already tried to make another extension but still didn't appear on the marketplace.
I Have another solution for pulling your Directus Cloud to another instance. Maybe you can try the v1.4.3 (latest version)

https://github.com/baguse/directus-extension-flow-manager/assets/36828138/15333814-7868-47d5-9f3e-342dd11bf464

**Comment by JayShoe** [comment]
Hello, I'm trying to get off the https://directus.cloud/

The only way to install extensions is with the marketplace. 

This extension used to show up but no longer does. 

I would need this in the marketplace to install it. 

I can not install it because it is not in the marketplace. 

It is not in the marketplace because it's not using sandbox mode. 

To expose this extension to users I would recommend making sure that it is in the marketplace. 

Currently it is not in the marketplace.

I might have to bail on my flows in the Directus cloud because I can't extract them. Or if I really want to try I'll learn how to revert this extension back to the older version which showed up on the marketplace. But then I need to learn how to publish to NPM, etc. This is something I was trying to avoid. 

I think it might even make sense for you to revert this entire extension and just make the current version BETA so that you can try it on local but it's still in the marketplace. 

The marketplace I'm referring to is in Directus>Settings>Marketplace. 
https://docs.directus.io/user-guide/marketplace/overview.html

This is where users go to "discover extensions". 

This extension is not in the marketplace. 

So I don't think I'm going to be able to export my flows. 

I hope this helps. Thanks for your time! I'll circle back if I come up with a solution.

**Comment by baguse** [comment]
> Hello, I'm trying to get off the https://directus.cloud/
> 
> The only way to install extensions is with the marketplace.
> 
> This extension used to show up but no longer does.
> 
> I would need this in the marketplace to install it.
> 
> I can not install it because it is not in the marketplace.
> 
> It is not in the marketplace because it's not using sandbox mode.
> 
> To expose this extension to users I would recommend making sure that it is in the marketplace.
> 
> Currently it is not in the marketplace.
> 
> I might have to bail on my flows in the Directus cloud because I can't extract them. Or if I really want to try I'll learn how to revert this extension back to the older version which showed up on the marketplace. But then I need to learn how to publish to NPM, etc. This is something I was trying to avoid.
> 
> I think it might even make sense for you to revert this entire extension and just make the current version BETA so that you can try it on local but it's still in the marketplace.
> 
> The marketplace I'm referring to is in Directus>Settings>Marketplace. https://docs.directus.io/user-guide/marketplace/overview.html
> 
> This is where users go to "discover extensions".
> 
> This extension is not in the marketplace.
> 
> So I don't think I'm going to be able to export my flows.
> 
> I hope this helps. Thanks for your time! I'll circle back if I come up with a solution.



> Hello, I'm trying to get off the https://directus.cloud/
> 
> The only way to install extensions is with the marketplace.
> 
> This extension used to show up but no longer does.
> 
> I would need this in the marketplace to install it.
> 
> I can not install it because it is not in the marketplace.
> 
> It is not in the marketplace because it's not using sandbox mode.
> 
> To expose this extension to users I would recommend making sure that it is in the marketplace.
> 
> Currently it is not in the marketplace.
> 
> I might have to bail on my flows in the Directus cloud because I can't extract them. Or if I really want to try I'll learn how to revert this extension back to the older version which showed up on the marketplace. But then I need to learn how to publish to NPM, etc. This is something I was trying to avoid.
> 
> I think it might even make sense for you to revert this entire extension and just make the current version BETA so that you can try it on local but it's still in the marketplace.
> 
> The marketplace I'm referring to is in Directus>Settings>Marketplace. https://docs.directus.io/user-guide/marketplace/overview.html
> 
> This is where users go to "discover extensions".
> 
> This extension is not in the marketplace.
> 
> So I don't think I'm going to be able to export my flows.
> 
> I hope this helps. Thanks for your time! I'll circle back if I come up with a solution.

Sorry about that, yeah I know the extension is not showing up on the marketplace because of the sandbox mode. I have tried to do anything about that.

1. Publish a new package to NPM with sandbox as activated 
2. Publish a new package to NPM with a single module only as before, but it's not even tracked into the directus registry

Both of them are not working, I published a new feature so you can pull your flow from the directus cloud to another directus instance

**Comment by baguse** [comment]
Hi @JayShoe, I am trying to add a new feature that help you to manage the flows from another instance kindly check. I will close this issue because for now, it's not possible to publish in the directus cloud marketplace due to the directus limitation itself
