### ISSUE TITLE
Flow Manager causing internal flows reload after every run

### ISSUE THREAD

**Issue by JoshTheDerf** [baguse/directus-extension-flow-manager#12]
Hi there!

We were trying to debug an issue where some of our flows would seem to disappear from the API during the middle of batch runs of other flows. We eventually tracked it down to this line in `directus-extension-flow-manager`:

- On every flow run, this extension updates flows with run information: https://github.com/baguse/directus-extension-flow-manager/blob/fe43f7bd65c6aea9f6db38fc46ff8e12e2dbc1bb/src/flow-manager-directus-flow-hook/index.ts#L51
- `flowsService.updateMany` triggers `flowManager.reload()` https://github.com/directus/directus/blob/cd67543f0577614229e3da47e3bfcb88f579158f/api/src/services/flows.ts#L42 which asynchronously reloads flows from the database.
- If a flow is run between `flowManager.unload()` and `flowManager.reload()`, it will not be found.

**Comment by baguse** [comment]
Hello, ah my bad thanks for helping me debug the issue. I will fix it soon, my plan is to update the flows using knex directly to avoid the side effect of the directus codebase. Wdyt?
