### ISSUE TITLE
Improve README 

### ISSUE THREAD

**Issue by lbraits** [baguse/directus-extension-flow-manager#14]
Hi,

First of all, thank you for this extension! We use it in a self-hosted Directus instance for the export/import feature flow, and it works pretty well for us.

In the last few weeks, we have noticed a recurring warning in our logs that seems to have appeared after an update of the extension:

    [01:00:01.041] WARN: update "directus_flows" set "flow_manager_last_run_at" = $1, "flow_manager_run_counter" = $2 where "id" = $3 - column "flow_manager_last_run_at" of relation "directus_flows" does not exist

After reading through some of the extension's code, we have figured out that these missing columns must be created manually via the Configure button on the extension's main page. I think it would be helpful to have this documented in the README as a required step when installing or updating the extension. Additionally, I am wondering if it would be possible to automate this process of migrating the database, for example, via a hook on one of Directus's init events, like the 'app.before' event?

Thank you!

**Comment by baguse** [comment]
Hi, thanks for trusting my extension and sorry for the trouble. Yes, I already noticed the extension problem. I already add the warning message on the instance, should I make the field creation automatically?

**Comment by lbraits** [comment]
Hi,
I think a warning or info would be nice, but automatic field creation would be even nicer :)

**Comment by baguse** [comment]
> Hi, I think a warning or info would be nice, but automatic field creation would be even nicer :)

Ok then, thanks for the input

**Comment by baguse** [comment]
Hi @lbraits, I fixed this issue on v1.4.5. Kindly check
