### ISSUE TITLE
Not visible?

### ISSUE THREAD

**Issue by BorisKamp** [baguse/directus-extension-flow-manager#15]
Hi!

I installed this package using this approach:
https://docs.directus.io/extensions/installing-extensions.html#installing-via-the-npm-registry

Now in extensions I see this:
<img width="1474" alt="Screenshot 2024-09-04 at 17 18 33" src="https://github.com/user-attachments/assets/23c33829-af31-4be6-bd56-0b4afd1acc52">

But I cannot see anything else, where do I export the flows?

My flows screen (http://localhost:8055/admin/settings/flows) is like this:
<img width="825" alt="Screenshot 2024-09-04 at 17 19 27" src="https://github.com/user-attachments/assets/a341ba1c-ebc5-42b3-a8bb-c5638211d532">

Thanks!

**Comment by baguse** [comment]
Hi @BorisKamp, Thanks for opening this issue. Have you already activated the module on the settings menu?
![image](https://github.com/user-attachments/assets/b9f567cc-0bc0-4cdf-93d2-f1f76f310f82)

**Comment by sri-repareo** [comment]
Hello! 
I am facing a similar issue. When I install it via the marketplace it installs but I am not able to use it : 
![image](https://github.com/user-attachments/assets/d3ae5da2-c0cf-4b0a-8565-a3b2eb618e6f)
![image](https://github.com/user-attachments/assets/248554de-9e0a-4f8e-ae92-6752de60543d)

**Comment by baguse** [comment]
> Hello! 
> I am facing a similar issue. When I install it via the marketplace it installs but I am not able to use it : 
> ![image](https://github.com/user-attachments/assets/d3ae5da2-c0cf-4b0a-8565-a3b2eb618e6f)
> ![image](https://github.com/user-attachments/assets/248554de-9e0a-4f8e-ae92-6752de60543d)
> 

Hi @sri-repareo ,I'm sorry for the inconvenience. Can you try installing it with npm command?

**Comment by delai** [comment]
> Hello! I am facing a similar issue. When I install it via the marketplace it installs but I am not able to use it : ![image](https://private-user-images.githubusercontent.com/147415902/371438155-d3ae5da2-c0cf-4b0a-8565-a3b2eb618e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDI2MDAsIm5iZiI6MTcyODY0MjMwMCwicGF0aCI6Ii8xNDc0MTU5MDIvMzcxNDM4MTU1LWQzYWU1ZGEyLWMwY2YtNGIwYS04NTY1LWEzYjJlYjYxOGU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMDI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzg4YjdiODdjZTg5MTNjMGE3NjdjNWQ1ZTVhYTkwNzNlN2FiMDVjN2M4MDZiNTY1ZjA1ZWRhODE4YTM3MTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._0mcahhgqa9cmcLR6zFvDzFOc78qeHx68bU5o7iKWF4) ![image](https://private-user-images.githubusercontent.com/147415902/371438244-248554de-9e0a-4f8e-ae92-6752de60543d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDI2MDAsIm5iZiI6MTcyODY0MjMwMCwicGF0aCI6Ii8xNDc0MTU5MDIvMzcxNDM4MjQ0LTI0ODU1NGRlLTllMGEtNGY4ZS1hZTkyLTY3NTJkZTYwNTQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMDI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTk2NzI1MjdiOWE4Njg2YjRkYzY3NWRlM2FmOTBiNTNjOWQzYzE1ODc5ODUyOGRlY2E3M2RjODFiNDIzYzY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xAOGGGxuLGICkRAe9EOLzRevrxT6Pr0PDqFYYXYQHpY)

same issue, finally installed by npm 

Some people might be like me, unsure where to execute 'npm install directus-extension-flow-manager' and what to do after that. Even the official documentation doesn't seem to explain it clearly. Here's a brief summary of what I did: I created an empty directory, ran the command there, then copied the 'directus-extension-flow-manager' folder from the generated 'node_modules' to the 'extensions' directory. As mentioned in https://github.com/baguse/directus-extension-flow-manager/issues/15#issuecomment-2332392723, you need to enable it in the settings. It took me quite a while to figure out that I needed to enable it in the settings.

**Comment by baguse** [comment]
Hello, Is anybody still facing the issue? Please let me know! @delai @BorisKamp @sri-repareo

**Comment by dimensi** [comment]
I'm facing

**Comment by baguse** [comment]
> I'm facing

What's your directus version?

**Comment by dimensi** [comment]
Hi, I have version 11.2, but I had a similar problem on the last version 11.1.8. Actually it feels like the problem is in directus itself, because I installed through the market or through npm different plugins and new plugins didn't appear, but old plugins weren't removed either. Even when I physically deleted a plugin that was already working, it was still in the system.
It's like directus has some kind of cache in the database

**Comment by baguse** [comment]
> Hi, I have version 11.2, but I had a similar problem on the last version 11.1.8. Actually it feels like the problem is in directus itself, because I installed through the market or through npm different plugins and new plugins didn't appear, but old plugins weren't removed either. Even when I physically deleted a plugin that was already working, it was still in the system. It's like directus has some kind of cache in the database

Ok thanks for the confirmation. Let me know if you all have another issue. For now We can wait the directus team to solve the problem
