### ISSUE TITLE
Bulk Enable/Disable via Select>Select All>

### ISSUE THREAD

**Issue by jshoemaker-gofer** [baguse/directus-extension-flow-manager#17]
Hello, 

I use the schema manager to deploy Directus. By default the import leaves the flows inactive. It would be nice to have the ability to enable (and disable) in bulk using the Select options on the flow manager. 

Thanks for the consideration!
Jay

**Comment by baguse** [comment]
Hi @jshoemaker-gofer , thanks for opening this FR. Ok, sure nice idea. I will add it for the next release. I'm so happy that you have an idea for this extension. If you have another idea or issue please let me know

Thanks!

**Comment by baguse** [comment]
Hi @jshoemaker-gofer, this feature was added on v1.4.9. Kindly check

**Comment by JayShoe** [comment]
Thank you! This is super helpful.

**Comment by baguse** [comment]
> Thank you! This is super helpful.

You are always welcome @JayShoe !
