### ISSUE TITLE
Request to Save Unused Flow Operations in Exports

### ISSUE THREAD

**Issue by JayShoe** [baguse/directus-extension-flow-manager#18]
Hello,

I’ve noticed that when exporting flows, any unused flow operations aren’t saved as part of the export. This can be challenging, as these unused operations often contain valuable data or configurations that I’ve temporarily bypassed for testing or other purposes.

Would it be possible to include unused flow operations in the flow backups? This addition would ensure no data is lost during exports and make the workflow more seamless.

Thank you for considering this request.

Best regards,
Jay

**Comment by baguse** [comment]
Hi @JayShoe, I just knew it. My bad. Thanks! I will add it to the next release
