### ISSUE TITLE
Unable to create configure flow manager fields

### ISSUE THREAD

**Issue by jeffersonsolorzano** [baguse/directus-extension-flow-manager#2]
When i try to add flow manager for the first time, directus sytem says:
```
 "type": "Error",
directus_container  |       "message": "alter table `directus_settings` add `flow_manager_categories` json null default '[]' - ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'flow_manager_categories' can't have a default value",
directus_container  |       "stack":
directus_container  |           Error: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'flow_manager_categories' can't have a default value```
```
<img width="593" alt="image" src="https://github.com/baguse/directus-extension-flow-manager/assets/65744166/cc5cbe4c-7416-4cda-a9bc-0881d6b9cf2e">

<img width="1313" alt="image" src="https://github.com/baguse/directus-extension-flow-manager/assets/65744166/ff23bb3d-7d02-49a0-81b4-ddcbf2c7bc1a">

**Comment by baguse** [comment]
![image](https://github.com/baguse/directus-extension-flow-manager/assets/36828138/5db67be6-e370-485b-86c5-c60952865d45)
Why don't you use this Configure button to do that?

**Comment by jeffersonsolorzano** [comment]
@baguse I tried doing that, when i clicked, it showed me the error above

**Comment by baguse** [comment]
What's version of the directus do you use? @jeffersonsolorzano

**Comment by jeffersonsolorzano** [comment]
Tried 10.8.3 and 10.9.0

**Comment by baguse** [comment]
> Tried 10.8.3 and 10.9.0

Ok thanks, I think the problem is coming from the mysql. I will try it

**Comment by baguse** [comment]
Hi @jeffersonsolorzano, could you tell me what version of your MySQL?

**Comment by jeffersonsolorzano** [comment]
Google cloud says mySQL 8.0

<img width="110" alt="image" src="https://github.com/baguse/directus-extension-flow-manager/assets/65744166/71c0c365-ef1e-46bc-877d-3df8030f053b">

**Comment by baguse** [comment]
Thanks @jeffersonsolorzano I have already reproduced your issue. I will fix it soon

**Comment by sideshot** [comment]
Hi I'm using mysql 8 and just got the same error.

[INTERNAL_SERVER_ERROR] { "code": "ER_BLOB_CANT_HAVE_DEFAULT", "errno": 1101, "sqlMessage": "BLOB, TEXT, GEOMETRY or JSON column 'flow_manager_categories' can't have a default value", "sqlState": "42000", "index": 0, "sql": "alter table `directus_settings` add `flow_manager_categories` json null default '[]'" }

**Comment by baguse** [comment]
> Hi I'm using mysql 8 and just got the same error.
> 
> [INTERNAL_SERVER_ERROR] { "code": "ER_BLOB_CANT_HAVE_DEFAULT", "errno": 1101, "sqlMessage": "BLOB, TEXT, GEOMETRY or JSON column 'flow_manager_categories' can't have a default value", "sqlState": "42000", "index": 0, "sql": "alter table `directus_settings` add `flow_manager_categories` json null default '[]'" }
> 

Yes, I found the issue. I will release it in the next release.

**Comment by baguse** [comment]
Hello the issue closed on v.1.4.1 Release @jeffersonsolorzano @sideshot
