### ISSUE TITLE
Show Status and Trigger

### ISSUE THREAD

**Issue by madc** [baguse/directus-extension-flow-manager#3]
This extension is a very nice addition to Directus.

It would really improve the usability, if information on how the flow is triggered (manual, cron, etc.) and if it is active or not would added.

**Comment by baguse** [comment]
Hello @madc, thanks for opening this issue. Nice idea, I will add the trigger type to the list. For the status, you can take a look at the color. If grayed then the flow is inactive.

Wdyt?

**Comment by baguse** [comment]
![image](https://github.com/baguse/directus-extension-flow-manager/assets/36828138/aa720309-608c-4539-a3df-5fbf972ed42e)
This is the WIP for this issue. @madc any thoughts?
