### ISSUE TITLE
Onclick open flow

### ISSUE THREAD

**Issue by arieanvdm** [baguse/directus-extension-flow-manager#4]
Hi, this flow manager is very handy!

I was only wondering if its possible to go to the flow by just an onclick on the flow. Maybe put the drag and drop handle in a different div where the onclick is not applied on? 

Thanks. Would save me some clicks 😉

**Comment by baguse** [comment]
Thank you for using this extension and for opening the issue. I will implement your idea for the next release. Stay tuned
