### ISSUE TITLE
Feature: Sort Flows by Last Ran

### ISSUE THREAD

**Issue by JayShoe** [baguse/directus-extension-flow-manager#6]
I would love to see an option to sort the flows by last ran date/time. This would keep the flows I'm working on at the top of the list.

**Comment by baguse** [comment]
Hello @JayShoe ,thanks for opening this issue. Interesting! But, I need to make a research to know if the directus provide the data for the sorting purpose

**Comment by baguse** [comment]
Hi, I have a news. It's possible. I will sort the data by last run date per category. Any thoughts?

**Comment by JayShoe** [comment]
I hope to have the flow in which was ran last towards the top of the list. Rather than sitting the categories. So I can easily identify it while working on a set of flows. There is also a last edited date that may also help to do what I'm hoping for. 

I use categories to group flows that work together. As you know there are many "trigger another flow" flows (unfortunately). 

Another option is a table view instead of item view and include columns for sort, flow, category, last run date. This way you can just sort it the way you want to (default being category and sort order). Plus if you can filter the table by category that would be amazing. Especially if it retained the last filter when reopening it. I think the table view might be my favorite idea tbh. This would solve a lot of my issues. 

Thanks for the consideration.

**Comment by baguse** [comment]
> I hope to have the flow in which was ran last towards the top of the list. Rather than sitting the categories. So I can easily identify it while working on a set of flows. There is also a last edited date that may also help to do what I'm hoping for. 
> 
> I use categories to group flows that work together. As you know there are many "trigger another flow" flows (unfortunately). 
> 
> Another option is a table view instead of item view and include columns for sort, flow, category, last run date. This way you can just sort it the way you want to (default being category and sort order). Plus if you can filter the table by category that would be amazing. Especially if it retained the last filter when reopening it. I think the table view might be my favorite idea tbh. This would solve a lot of my issues. 
> 
> Thanks for the consideration. 

Ah thanks for great explanation. I will make a feature that take your comments as reference. Stay tuned

**Comment by baguse** [comment]
Hello the new feature added on v.1.4.1 Release
