### ISSUE TITLE
Does this extension support Directus 10?

### ISSUE THREAD

**Issue by akurdyukov** [baguse/directus-extension-flow-manager#7]
Unfortunately I do not see left menu item with zap icon in my Directus 10.10.5 interface after I installed this extension. Does it support latest version?

**Comment by baguse** [comment]
Hello @akurdyukov ,thanks for creating this issue. Can you provide your system details? The nodejs version and Do you instaling the extension using npm or using the extension folder?

**Comment by akurdyukov** [comment]
nodejs v20.8.0
directus v10.10.5

I tried both marketplace (beta) and npm installation. On start I see `Loaded extensions: directus-extension-flow-manager` in the log.

**Comment by baguse** [comment]
Have you already activated the Module? @akurdyukov 
![image](https://github.com/baguse/directus-extension-flow-manager/assets/36828138/c0f3c87a-36ab-44ab-9d20-27494ab5114a)

**Comment by akurdyukov** [comment]
Oops, no, I didn't knew I need to enable it. I put the check and now everything seems to work ok. Thanks!

**Comment by baguse** [comment]
Cool, I will close this issue. Thanks!
