### ISSUE TITLE
Roles Manager

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [baguse/directus-extension-flow-manager#8]
Is it possible to add an import/export role manager or to create a seperate package?

**Comment by baguse** [comment]
Hello, thanks for opening the issue. Hmmm I think it needs to develop another extension

**Comment by NilsBaumgartner1994** [comment]
That would be great. I think a lot of people would use this.Beste Grüße,Nils BaumgartnerAm 19.04.2024 um 03:47 schrieb Bagus Andreanto ***@***.***>:﻿
Hello, thanks for opening the issue. Hmmm I think it needs to develop another extension

**Comment by NilsBaumgartner1994** [comment]
Yes please. Could you keep me updated or mention me there?

**Comment by baguse** [comment]
> Yes please. Could you keep me updated or mention me there?

Sorry to say, but unfortunately I don't have a time to do that for now. I think there are some extension that can do backup and restore using CLI mode.
